create table ALLOCATION_585279
(
NAME VARCHAR(20),
ID INT,
DEPT VARCHAR(20),
TYPE1 VARCHAR(20),
DAYS INT,
COMMENTS VARCHAR(40)
);
SELECT * from ALLOCATION_585279
commit

create table MEGAWARE_ALLOCATION_GROUPE_2
(
EMPLOYEE_NAME VARCHAR(20),
ID INT,
DESIGNATION VARCHAR(20),
TYPE1 VARCHAR(20),
DAYS INT,
COMMENTS VARCHAR(40)
);
SELECT * from MEGAWARE_ALLOCATION_GROUPE_2;
INSERT INTO MEGAWARE_ALLOCATION_GROUPE_2 VALUES('PARAS JAIN','585030','ASET','FLEXIBLE',1,'JYADA SHUTTI NH');
commit

select * from megaware_groupe_2;
SELECT * FROM MEGAWARE_GROUPE_2 WHERE FIRST_NAME='MADHU'; 